"""add users_count

Revision ID: 3b9252b28f45
Revises: 0cdc72413cb6
Create Date: 2023-02-20 18:07:34.566741

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3b9252b28f45'
down_revision = '0cdc72413cb6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_activity',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('user_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_activity_id'), 'users_activity', ['id'], unique=False)
    op.drop_index('ix_event_logs_id', table_name='event_logs')
    op.drop_table('event_logs')
    op.drop_index('ix_messages_id', table_name='messages')
    op.drop_table('messages')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_uuid', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('message_type', postgresql.ENUM('READ', 'UPDATE', 'UNDEFINED', name='messagetype'), autoincrement=False, nullable=True),
    sa.Column('message_intent', postgresql.ENUM('MONDAY_BELOW', 'MONDAY_ABOVE', 'TUESDAY_BELOW', 'TUESDAY_ABOVE', 'WEDNESDAY_BELOW', 'WEDNESDAY_ABOVE', 'THURSDAY_BELOW', 'THURSDAY_ABOVE', 'FRIDAY_BELOW', 'FRIDAY_ABOVE', 'SATURDAY_BELOW', 'SATURDAY_ABOVE', 'SETTINGS', 'GROUP', 'COMPANION', 'UPTIME', 'UNDEFINED', name='messageintent'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.uuid'], name='messages_user_uuid_fkey'),
    sa.PrimaryKeyConstraint('id', name='messages_pkey')
    )
    op.create_index('ix_messages_id', 'messages', ['id'], unique=False)
    op.create_table('event_logs',
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('data', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('event_type', postgresql.ENUM('CREATE', 'READ', 'UPDATE', 'DELETE', name='eventlogtype'), autoincrement=False, nullable=True),
    sa.Column('event_action', postgresql.ENUM('SPREADSHEET', 'CLASS', 'OTHER', name='eventlogaction'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='event_logs_pkey')
    )
    op.create_index('ix_event_logs_id', 'event_logs', ['id'], unique=False)
    op.drop_index(op.f('ix_users_activity_id'), table_name='users_activity')
    op.drop_table('users_activity')
    # ### end Alembic commands ###
