"""added new table hyperlinks

Revision ID: 4900652dabea
Revises: a265db8b5269
Create Date: 2022-03-11 02:48:24.160712

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '4900652dabea'
down_revision = 'a265db8b5269'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'hyperlinks',
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('class_id', sa.Integer(), nullable=True),
        sa.Column('hyperlink', sa.String(length=1000), nullable=True),
        sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hyperlinks_id'), 'hyperlinks', ['id'], unique=False)
    op.drop_column('classes', 'hyperlinks')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classes', sa.Column('hyperlinks', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_hyperlinks_id'), table_name='hyperlinks')
    op.drop_table('hyperlinks')
    # ### end Alembic commands ###
