"""users_fix

Revision ID: 4bca217e879f
Revises: 1a0f38175529
Create Date: 2022-03-13 22:32:02.603626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bca217e879f'
down_revision = '1a0f38175529'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_uuid', table_name='users')
    op.execute("ALTER TABLE users ALTER COLUMN vk_id TYPE INTEGER USING vk_id::integer")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_uuid', 'users', ['uuid'], unique=False)
    op.execute("ALTER TABLE users ALTER COLUMN vk_id TYPE STRING USING vk_id::string")
    # ### end Alembic commands ###
