"""deleted tables: classes and hyperlinks

Revision ID: 5cc9083db9b7
Revises: 5f2e53bab951
Create Date: 2022-03-12 00:45:13.940416

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5cc9083db9b7'
down_revision = '5f2e53bab951'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_hyperlinks_id', table_name='hyperlinks')
    op.drop_index('ix_classes_id', table_name='classes')
    op.drop_table('hyperlinks')
    op.drop_table('classes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'hyperlinks',
        sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('class_id', sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('hyperlink', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(['class_id'], ['classes.id'], name='hyperlinks_class_id_fkey'),
        sa.PrimaryKeyConstraint('id', name='hyperlinks_pkey')
    )
    op.create_index('ix_hyperlinks_id', 'hyperlinks', ['id'], unique=False)
    op.create_table(
        'classes',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column('week_day_index', sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('above_line', sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint('id', name='classes_pkey')
    )
    op.create_index('ix_classes_id', 'classes', ['id'], unique=False)
    # ### end Alembic commands ###
