"""updated class model

Revision ID: 810ce589dcd5
Revises: ecc9d3b9e57b
Create Date: 2022-03-11 02:30:16.859696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '810ce589dcd5'
down_revision = 'ecc9d3b9e57b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classes', sa.Column('week_day_index', sa.Integer(), nullable=True))
    op.add_column('classes', sa.Column('above_line', sa.Boolean(), nullable=True))
    op.drop_constraint('classes_absolute_index_key', 'classes', type_='unique')
    op.drop_column('classes', 'absolute_index')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classes', sa.Column('absolute_index', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_unique_constraint('classes_absolute_index_key', 'classes', ['absolute_index'])
    op.drop_column('classes', 'above_line')
    op.drop_column('classes', 'week_day_index')
    # ### end Alembic commands ###
