"""added timestamp mixin to classes table

Revision ID: 84f3d45d1f34
Revises: 80e9fc59feae
Create Date: 2022-03-05 14:25:36.794104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84f3d45d1f34'
down_revision = '80e9fc59feae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classes', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('classes', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('classes', 'updated_at')
    op.drop_column('classes', 'created_at')
    # ### end Alembic commands ###
