"""renamed hyperlink

Revision ID: a265db8b5269
Revises: 810ce589dcd5
Create Date: 2022-03-11 02:31:30.598961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a265db8b5269'
down_revision = '810ce589dcd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classes', sa.Column('hyperlinks', sa.String(length=1000), nullable=True))
    op.drop_column('classes', 'links')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classes', sa.Column('links', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('classes', 'hyperlinks')
    # ### end Alembic commands ###
