"""added google creds table

Revision ID: acaf1083c23f
Revises: 84f3d45d1f34
Create Date: 2022-03-05 15:15:19.681451

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'acaf1083c23f'
down_revision = '84f3d45d1f34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('google_credentials',
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('service_name', sa.String(length=255), nullable=True),
                    sa.Column('credentials', sa.String(length=1000), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('credentials'),
                    sa.UniqueConstraint('service_name')
                    )
    op.create_index(op.f('ix_google_credentials_id'), 'google_credentials', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_google_credentials_id'), table_name='google_credentials')
    op.drop_table('google_credentials')
    # ### end Alembic commands ###
