"""deleted new table

Revision ID: e0eb5aa5482b
Revises: dae43c7299d7
Create Date: 2022-03-06 00:14:56.972124

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'e0eb5aa5482b'
down_revision = 'dae43c7299d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_spreadsheet_version_id', table_name='spreadsheet_version')
    op.drop_table('spreadsheet_version')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spreadsheet_version',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('version', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('id', name='spreadsheet_version_pkey')
                    )
    op.create_index('ix_spreadsheet_version_id', 'spreadsheet_version', ['id'], unique=False)
    # ### end Alembic commands ###
