"""logging_upd

Revision ID: ecc9d3b9e57b
Revises: 4f72d02d8422
Create Date: 2022-03-06 02:48:08.910001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecc9d3b9e57b'
down_revision = '4f72d02d8422'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    foo = """create type eventlogtype as enum ('CREATE', 'READ', 'UPDATE', 'DELETE');"""
    bar = """create type eventlogaction as enum ('SPREADSHEET',
    'CLASS',
    'OTHER');"""
    op.execute(foo)
    op.execute(bar)
    op.add_column('event_logs', sa.Column('event_type', sa.Enum('CREATE', 'READ', 'UPDATE', 'DELETE', 'UNDEFINED', name='eventlogtype'), nullable=True))
    op.add_column('event_logs', sa.Column('event_action', sa.Enum('SPREADSHEET', 'CLASS', 'OTHER', name='eventlogaction'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_logs', 'event_action')
    op.drop_column('event_logs', 'event_type')
    op.execute("drop type eventlogtype")
    op.execute("drop type eventlogaction")
    # ### end Alembic commands ###
