"""add creds

Revision ID: 0002
Revises: 0001
Create Date: 2023-09-03 12:08:00.739936

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = "0002"
down_revision = "0001"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "credentials",
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("service_name", sa.String(), nullable=False),
        sa.Column("credentials", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("service_name"),
    )
    op.create_index(
        op.f("ix_credentials_service_name"), "credentials", ["service_name"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_credentials_service_name"), table_name="credentials")
    op.drop_table("credentials")
    # ### end Alembic commands ###
