"""new telemetry

Revision ID: 0005
Revises: 0004
Create Date: 2023-09-03 21:23:02.554610

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0005"
down_revision = "0004"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users_activity", sa.Column("new_group", sa.Integer(), nullable=True))
    op.add_column("users_activity", sa.Column("pattern", sa.String(), nullable=True))
    op.add_column("users_activity", sa.Column("correct", sa.Boolean(), nullable=True))
    op.drop_column("users_activity", "requested_group")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users_activity",
        sa.Column("requested_group", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_column("users_activity", "correct")
    op.drop_column("users_activity", "pattern")
    op.drop_column("users_activity", "new_group")
    # ### end Alembic commands ###
