"""add buttons to metrics

Revision ID: 0007
Revises: 0006
Create Date: 2023-09-05 02:10:18.662513

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0007"
down_revision = "0006"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users_activity", sa.Column("button", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users_activity", "button")
    # ### end Alembic commands ###
