"""add user source

Revision ID: 0008
Revises: 0007
Create Date: 2023-09-11 19:19:36.966002

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0008"
down_revision = "0007"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("source", sa.String()))
    op.add_column("users_activity", sa.Column("source", sa.String()))

    op.execute("update users set source = 'vk'")
    op.execute("update users_activity set source = 'vk'")

    op.alter_column("users", "source", existing_type=sa.VARCHAR(), nullable=False)

    op.alter_column("users_activity", "source", existing_type=sa.VARCHAR(), nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "password", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_column("users", "source")
    # ### end Alembic commands ###
