"""fix

Revision ID: 0010
Revises: 0009
Create Date: 2023-10-15 01:09:20.034245

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0010"
down_revision = "0009"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users_activity", "user_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("users_activity_legacy", "user_count", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users_activity_legacy", "user_count", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column("users_activity", "user_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###
